---
- name: Configure CI server
  hosts: ci-server
  become: yes
  
  vars:
    jenkins_plugins:
      - build-pipeline-plugin
      - build-monitor-plugin
    jenkins_process_user: ec2-user
  roles:
    - curl
    - git
    - java
    - role: jenkins
      vars:
        jenkins_version: "2.303"

- name: Configure slave
  hosts: agent
  become: yes
  roles:
    - curl
    - java
    - jenkins-slave
  tags: jenkins-slave
